services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: piyush
      POSTGRES_PASSWORD: piyush
      PGDATA: /data/postgres
      TZ: Asia/Kolkata
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#      - 9411:9411
#    networks:
#      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin:


#services:
#  mysql:
#    container_name: mysql_container
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: piyush
#      MYSQL_DATABASE: piyush
#      MYSQL_USER: piyush
#      MYSQL_PASSWORD: piyush
#    volumes:
#      - mysql_data:/var/lib/mysql
#    ports:
#      - "3307:3306"
#    networks:
#      - mysql
#    restart: unless-stopped
#
#  phpmyadmin:
#    container_name: phpmyadmin_container
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: piyush
#    ports:
#      - "8484:80"
#    networks:
#      - mysql
#    restart: unless-stopped
#
#networks:
#  mysql:
#    driver: bridge
#
#volumes:
#  mysql_data: