spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: piyush
    password: piyush
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true


logging:
  level:
    root: INFO
    com.ecommerce.user: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10 # Last 10 calls are required to decide circuit is Open/closed.
        minimumNumberOfCalls: 5 # Minimum number of calls required before the circuit breaker starts to evaluating failure rates.
        permittedNumberOfCallsInHalfOpenState: 3 # Half Open state only 3 request are allowed, before deciding state is Open/Closed.
        waitDurationInOpenState: 10s # Circuit remains open for 10s for rejecting calls before it is in Open State.
        failureRateThreshold: 50 # This is percentage here, if 50% or more calls fail teh circuit breaker opens and begin rejecting the calls
        automaticTransitionFromOpenToHalfOpenEnabled: true # After 10sec, it will automatically will transition from Open to Half Open State.
        slidingWindowType: count_based
  retry:
    instances:
      retryBreaker:
        maxAttempts: 5
        waitDuration: 500ms



